# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ana_sayfa.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_sifreOlusturSifreleKaydet(object):
    def setupUi(self, sifreOlusturSifreleKaydet):
        sifreOlusturSifreleKaydet.setObjectName("sifreOlusturSifreleKaydet")
        sifreOlusturSifreleKaydet.resize(494, 724)
        sifreOlusturSifreleKaydet.setAutoFillBackground(False)
        sifreOlusturSifreleKaydet.setStyleSheet("QMainWindow {\n"
"    background-color:rgb(82, 82, 82);\n"
"}\n"
"QTextEdit {\n"
"    background-color:rgb(42, 42, 42);\n"
"    color: rgb(0, 255, 0);\n"
"}\n"
"QPushButton{\n"
"    border-style: solid;\n"
"    border-color: #050a0e;\n"
"    border-width: 1px;\n"
"    border-radius: 5px;\n"
"    color: #d3dae3;\n"
"    padding: 2px;\n"
"    background-color: #100E19;\n"
"}\n"
"QPushButton::default{\n"
"    border-style: solid;\n"
"    border-color: #050a0e;\n"
"    border-width: 1px;\n"
"    border-radius: 5px;\n"
"    color: #FFFFFF;\n"
"    padding: 2px;\n"
"    background-color: #151a1e;\n"
"}\n"
"QPushButton:hover{\n"
"    border-style: solid;\n"
"    border-top-color: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:1, stop:0 #C0DB50, stop:0.4 #C0DB50, stop:0.5 #100E19, stop:1 #100E19);\n"
"    border-bottom-color: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:1, stop:0 #100E19, stop:0.5 #100E19, stop:0.6 #C0DB50, stop:1 #C0DB50);\n"
"    border-left-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #C0DB50, stop:0.3 #C0DB50, stop:0.7 #100E19, stop:1 #100E19);\n"
"    border-right-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 #C0DB50, stop:0.3 #C0DB50, stop:0.7 #100E19, stop:1 #100E19);\n"
"    border-width: 2px;\n"
"    border-radius: 1px;\n"
"    color: #d3dae3;\n"
"    padding: 2px;\n"
"}\n"
"QPushButton:pressed{\n"
"    border-style: solid;\n"
"    border-top-color: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:1, stop:0 #d33af1, stop:0.4 #d33af1, stop:0.5 #100E19, stop:1 #100E19);\n"
"    border-bottom-color: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:1, stop:0 #100E19, stop:0.5 #100E19, stop:0.6 #d33af1, stop:1 #d33af1);\n"
"    border-left-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #d33af1, stop:0.3 #d33af1, stop:0.7 #100E19, stop:1 #100E19);\n"
"    border-right-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 #d33af1, stop:0.3 #d33af1, stop:0.7 #100E19, stop:1 #100E19);\n"
"    border-width: 2px;\n"
"    border-radius: 1px;\n"
"    color: #d3dae3;\n"
"    padding: 2px;\n"
"}\n"
"QLineEdit {\n"
"    border-width: 1px; border-radius: 4px;\n"
"    border-color: rgb(58, 58, 58);\n"
"    border-style: inset;\n"
"    padding: 0 8px;\n"
"    color: rgb(255, 255, 255);\n"
"    background:rgb(100, 100, 100);\n"
"    selection-background-color: rgb(187, 187, 187);\n"
"    selection-color: rgb(60, 63, 65);\n"
"}\n"
"QLabel {\n"
"    color:rgb(255,255,255);    \n"
"}\n"
"QProgressBar {\n"
"    text-align: center;\n"
"    color: rgb(240, 240, 240);\n"
"    border-width: 1px; \n"
"    border-radius: 10px;\n"
"    border-color: rgb(58, 58, 58);\n"
"    border-style: inset;\n"
"    background-color:rgb(77,77,77);\n"
"}\n"
"QProgressBar::chunk {\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:0.7, x2:0.5, y2:0.3, stop:0 rgba(87, 97, 106, 255), stop:1 rgba(93, 103, 113, 255));\n"
"    border-radius: 5px;\n"
"}\n"
"QMenuBar {\n"
"    background:rgb(82, 82, 82);\n"
"}\n"
"QMenuBar::item {\n"
"    color:rgb(223,219,210);\n"
"    spacing: 3px;\n"
"    padding: 1px 4px;\n"
"    background: transparent;\n"
"}\n"
"\n"
"QMenuBar::item:selected {\n"
"    background:rgb(115, 115, 115);\n"
"}\n"
"QMenu::item:selected {\n"
"    color:rgb(255,255,255);\n"
"    border-width:2px;\n"
"    border-style:solid;\n"
"    padding-left:18px;\n"
"    padding-right:8px;\n"
"    padding-top:2px;\n"
"    padding-bottom:3px;\n"
"    background:qlineargradient(spread:pad, x1:0.5, y1:0.7, x2:0.5, y2:0.3, stop:0 rgba(87, 97, 106, 255), stop:1 rgba(93, 103, 113, 255));\n"
"    border-top-color: qlineargradient(spread:pad, x1:0.5, y1:0.6, x2:0.5, y2:0.4, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(62, 62, 62, 255));\n"
"    border-right-color: qlineargradient(spread:pad, x1:0.4, y1:0.5, x2:0.6, y2:0.5, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(62, 62, 62, 255));\n"
"    border-left-color: qlineargradient(spread:pad, x1:0.6, y1:0.5, x2:0.4, y2:0.5, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(62, 62, 62, 255));\n"
"    border-bottom-color: rgb(58, 58, 58);\n"
"    border-bottom-width: 1px;\n"
"}\n"
"QMenu::item {\n"
"    color:rgb(223,219,210);\n"
"    background-color:rgb(78,78,78);\n"
"    padding-left:20px;\n"
"    padding-top:4px;\n"
"    padding-bottom:4px;\n"
"    padding-right:10px;\n"
"}\n"
"QMenu{\n"
"    background-color:rgb(78,78,78);\n"
"}\n"
"QTabWidget {\n"
"    color:rgb(0,0,0);\n"
"    background-color:rgb(247,246,246);\n"
"}\n"
"QTabWidget::pane {\n"
"        border-color: rgb(77,77,77);\n"
"        background-color:rgb(101,101,101);\n"
"        border-style: solid;\n"
"        border-width: 1px;\n"
"        border-radius: 6px;\n"
"}\n"
"QTabBar::tab {\n"
"    padding:2px;\n"
"    color:rgb(250,250,250);\n"
"      background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(77, 77, 77, 255), stop:1 rgba(97, 97, 97, 255));\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"      border-top-right-radius:4px;\n"
"   border-top-left-radius:4px;\n"
"    border-top-color: qlineargradient(spread:pad, x1:0.5, y1:0.6, x2:0.5, y2:0.4, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(95, 92, 93, 255));\n"
"    border-right-color: qlineargradient(spread:pad, x1:0.4, y1:0.5, x2:0.6, y2:0.5, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(95, 92, 93, 255));\n"
"    border-left-color: qlineargradient(spread:pad, x1:0.6, y1:0.5, x2:0.4, y2:0.5, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(95, 92, 93, 255));\n"
"    border-bottom-color: rgb(101,101,101);\n"
"}\n"
"QTabBar::tab:selected, QTabBar::tab:last:selected, QTabBar::tab:hover {\n"
"      background-color:rgb(101,101,101);\n"
"      margin-left: 0px;\n"
"      margin-right: 1px;\n"
"}\n"
"QTabBar::tab:!selected {\n"
"        margin-top: 1px;\n"
"        margin-right: 1px;\n"
"}\n"
"QCheckBox {\n"
"    color:rgb(223,219,210);\n"
"    padding: 2px;\n"
"}\n"
"QCheckBox:hover {\n"
"    border-radius:4px;\n"
"    border-style:solid;\n"
"    padding-left: 1px;\n"
"    padding-right: 1px;\n"
"    padding-bottom: 1px;\n"
"    padding-top: 1px;\n"
"    border-width:1px;\n"
"    border-color: rgb(87, 97, 106);\n"
"    background-color:qlineargradient(spread:pad, x1:0.5, y1:0.7, x2:0.5, y2:0.3, stop:0 rgba(87, 97, 106, 150), stop:1 rgba(93, 103, 113, 150));\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked {\n"
"    border-radius:4px;\n"
"    border-style:solid;\n"
"    border-width:1px;\n"
"    border-color: rgb(87, 97, 106);\n"
"      background-color:rgb(255,255,255);\n"
"}\n"
"QStatusBar {\n"
"    color:rgb(240,240,240);\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(sifreOlusturSifreleKaydet)
        self.centralwidget.setAutoFillBackground(True)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.hata_labeli = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hata_labeli.sizePolicy().hasHeightForWidth())
        self.hata_labeli.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.hata_labeli.setFont(font)
        self.hata_labeli.setStyleSheet("background-color:rgb(82, 82, 82);\n"
"color: rgb(255,102,0);")
        self.hata_labeli.setAlignment(QtCore.Qt.AlignCenter)
        self.hata_labeli.setObjectName("hata_labeli")
        self.verticalLayout.addWidget(self.hata_labeli)
        self.sekmeler = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sekmeler.sizePolicy().hasHeightForWidth())
        self.sekmeler.setSizePolicy(sizePolicy)
        self.sekmeler.setAutoFillBackground(False)
        self.sekmeler.setStyleSheet("")
        self.sekmeler.setTabBarAutoHide(True)
        self.sekmeler.setObjectName("sekmeler")
        self.tabAciklama = QtWidgets.QWidget()
        self.tabAciklama.setObjectName("tabAciklama")
        self.formLayout = QtWidgets.QFormLayout(self.tabAciklama)
        self.formLayout.setObjectName("formLayout")
        self.textEditProgramAciklama = QtWidgets.QTextEdit(self.tabAciklama)
        self.textEditProgramAciklama.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEditProgramAciklama.sizePolicy().hasHeightForWidth())
        self.textEditProgramAciklama.setSizePolicy(sizePolicy)
        self.textEditProgramAciklama.setMinimumSize(QtCore.QSize(0, 450))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.textEditProgramAciklama.setFont(font)
        self.textEditProgramAciklama.setObjectName("textEditProgramAciklama")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.textEditProgramAciklama)
        self.sekmeler.addTab(self.tabAciklama, "")
        self.tabSifreOlustur = QtWidgets.QWidget()
        self.tabSifreOlustur.setAutoFillBackground(False)
        self.tabSifreOlustur.setObjectName("tabSifreOlustur")
        self.formLayout_2 = QtWidgets.QFormLayout(self.tabSifreOlustur)
        self.formLayout_2.setObjectName("formLayout_2")
        self.baslik1 = QtWidgets.QLabel(self.tabSifreOlustur)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.baslik1.sizePolicy().hasHeightForWidth())
        self.baslik1.setSizePolicy(sizePolicy)
        self.baslik1.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.baslik1.setFont(font)
        self.baslik1.setAutoFillBackground(False)
        self.baslik1.setTextFormat(QtCore.Qt.AutoText)
        self.baslik1.setScaledContents(False)
        self.baslik1.setAlignment(QtCore.Qt.AlignCenter)
        self.baslik1.setObjectName("baslik1")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.baslik1)
        self.sifreUzunlugu_aciklama = QtWidgets.QLabel(self.tabSifreOlustur)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.sifreUzunlugu_aciklama.setFont(font)
        self.sifreUzunlugu_aciklama.setAutoFillBackground(False)
        self.sifreUzunlugu_aciklama.setAlignment(QtCore.Qt.AlignCenter)
        self.sifreUzunlugu_aciklama.setObjectName("sifreUzunlugu_aciklama")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.sifreUzunlugu_aciklama)
        self.sifreUzunluguLine = QtWidgets.QLineEdit(self.tabSifreOlustur)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sifreUzunluguLine.sizePolicy().hasHeightForWidth())
        self.sifreUzunluguLine.setSizePolicy(sizePolicy)
        self.sifreUzunluguLine.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.sifreUzunluguLine.setFont(font)
        self.sifreUzunluguLine.setMaxLength(4)
        self.sifreUzunluguLine.setObjectName("sifreUzunluguLine")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.sifreUzunluguLine)
        self.turkceKarakterChbox = QtWidgets.QCheckBox(self.tabSifreOlustur)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.turkceKarakterChbox.setFont(font)
        self.turkceKarakterChbox.setObjectName("turkceKarakterChbox")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.turkceKarakterChbox)
        self.ozelKarakterChbox = QtWidgets.QCheckBox(self.tabSifreOlustur)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.ozelKarakterChbox.setFont(font)
        self.ozelKarakterChbox.setAutoFillBackground(False)
        self.ozelKarakterChbox.setAutoRepeat(False)
        self.ozelKarakterChbox.setObjectName("ozelKarakterChbox")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.ozelKarakterChbox)
        self.rakamChbox = QtWidgets.QCheckBox(self.tabSifreOlustur)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.rakamChbox.setFont(font)
        self.rakamChbox.setAutoFillBackground(False)
        self.rakamChbox.setChecked(False)
        self.rakamChbox.setObjectName("rakamChbox")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.rakamChbox)
        self.sifreOlusturButon = QtWidgets.QPushButton(self.tabSifreOlustur)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(35)
        sizePolicy.setHeightForWidth(self.sifreOlusturButon.sizePolicy().hasHeightForWidth())
        self.sifreOlusturButon.setSizePolicy(sizePolicy)
        self.sifreOlusturButon.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.sifreOlusturButon.setFont(font)
        self.sifreOlusturButon.setAutoFillBackground(False)
        self.sifreOlusturButon.setObjectName("sifreOlusturButon")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.sifreOlusturButon)
        self.sifreCiktisi = QtWidgets.QLineEdit(self.tabSifreOlustur)
        self.sifreCiktisi.setMinimumSize(QtCore.QSize(250, 100))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.sifreCiktisi.setFont(font)
        self.sifreCiktisi.setText("")
        self.sifreCiktisi.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.sifreCiktisi.setDragEnabled(False)
        self.sifreCiktisi.setObjectName("sifreCiktisi")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.SpanningRole, self.sifreCiktisi)
        self.sekmeler.addTab(self.tabSifreOlustur, "")
        self.tabSifreKaydetListele = QtWidgets.QWidget()
        self.tabSifreKaydetListele.setAutoFillBackground(False)
        self.tabSifreKaydetListele.setObjectName("tabSifreKaydetListele")
        self.gridLayout = QtWidgets.QGridLayout(self.tabSifreKaydetListele)
        self.gridLayout.setObjectName("gridLayout")
        self.sifreListelemeTablo = QtWidgets.QTableWidget(self.tabSifreKaydetListele)
        self.sifreListelemeTablo.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sifreListelemeTablo.sizePolicy().hasHeightForWidth())
        self.sifreListelemeTablo.setSizePolicy(sizePolicy)
        self.sifreListelemeTablo.setMinimumSize(QtCore.QSize(0, 0))
        self.sifreListelemeTablo.setSizeIncrement(QtCore.QSize(0, 0))
        self.sifreListelemeTablo.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.sifreListelemeTablo.setFont(font)
        self.sifreListelemeTablo.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.sifreListelemeTablo.setAutoScroll(True)
        self.sifreListelemeTablo.setAutoScrollMargin(10)
        self.sifreListelemeTablo.setGridStyle(QtCore.Qt.SolidLine)
        self.sifreListelemeTablo.setRowCount(100)
        self.sifreListelemeTablo.setColumnCount(2)
        self.sifreListelemeTablo.setObjectName("sifreListelemeTablo")
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.sifreListelemeTablo.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.sifreListelemeTablo.setHorizontalHeaderItem(1, item)
        self.sifreListelemeTablo.horizontalHeader().setCascadingSectionResizes(False)
        self.sifreListelemeTablo.verticalHeader().setCascadingSectionResizes(False)
        self.gridLayout.addWidget(self.sifreListelemeTablo, 10, 1, 1, 1)
        self.sifresizMesajLine = QtWidgets.QLineEdit(self.tabSifreKaydetListele)
        self.sifresizMesajLine.setObjectName("sifresizMesajLine")
        self.gridLayout.addWidget(self.sifresizMesajLine, 6, 1, 1, 1)
        self.sifreAnahtar = QtWidgets.QLineEdit(self.tabSifreKaydetListele)
        self.sifreAnahtar.setText("")
        self.sifreAnahtar.setObjectName("sifreAnahtar")
        self.gridLayout.addWidget(self.sifreAnahtar, 8, 1, 1, 1)
        self.dosyaYoluLink = QtWidgets.QLabel(self.tabSifreKaydetListele)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dosyaYoluLink.sizePolicy().hasHeightForWidth())
        self.dosyaYoluLink.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.dosyaYoluLink.setFont(font)
        self.dosyaYoluLink.setAutoFillBackground(False)
        self.dosyaYoluLink.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.dosyaYoluLink.setObjectName("dosyaYoluLink")
        self.gridLayout.addWidget(self.dosyaYoluLink, 1, 1, 1, 1)
        self.sifreAciklamaLine = QtWidgets.QLineEdit(self.tabSifreKaydetListele)
        self.sifreAciklamaLine.setObjectName("sifreAciklamaLine")
        self.gridLayout.addWidget(self.sifreAciklamaLine, 4, 1, 1, 1)
        self.dosyaYoluButon = QtWidgets.QPushButton(self.tabSifreKaydetListele)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(30)
        sizePolicy.setHeightForWidth(self.dosyaYoluButon.sizePolicy().hasHeightForWidth())
        self.dosyaYoluButon.setSizePolicy(sizePolicy)
        self.dosyaYoluButon.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.dosyaYoluButon.setFont(font)
        self.dosyaYoluButon.setAutoFillBackground(False)
        self.dosyaYoluButon.setObjectName("dosyaYoluButon")
        self.gridLayout.addWidget(self.dosyaYoluButon, 1, 0, 1, 1)
        self.sifreAciklama = QtWidgets.QLabel(self.tabSifreKaydetListele)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(40)
        sizePolicy.setHeightForWidth(self.sifreAciklama.sizePolicy().hasHeightForWidth())
        self.sifreAciklama.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.sifreAciklama.setFont(font)
        self.sifreAciklama.setAutoFillBackground(False)
        self.sifreAciklama.setAlignment(QtCore.Qt.AlignCenter)
        self.sifreAciklama.setObjectName("sifreAciklama")
        self.gridLayout.addWidget(self.sifreAciklama, 4, 0, 1, 1)
        self.sifreAciklamaSifre = QtWidgets.QLabel(self.tabSifreKaydetListele)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(40)
        sizePolicy.setHeightForWidth(self.sifreAciklamaSifre.sizePolicy().hasHeightForWidth())
        self.sifreAciklamaSifre.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.sifreAciklamaSifre.setFont(font)
        self.sifreAciklamaSifre.setAutoFillBackground(False)
        self.sifreAciklamaSifre.setAlignment(QtCore.Qt.AlignCenter)
        self.sifreAciklamaSifre.setObjectName("sifreAciklamaSifre")
        self.gridLayout.addWidget(self.sifreAciklamaSifre, 6, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.tabSifreKaydetListele)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 8, 0, 1, 1)
        self.sifreGosterButon = QtWidgets.QPushButton(self.tabSifreKaydetListele)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(50)
        sizePolicy.setHeightForWidth(self.sifreGosterButon.sizePolicy().hasHeightForWidth())
        self.sifreGosterButon.setSizePolicy(sizePolicy)
        self.sifreGosterButon.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.sifreGosterButon.setFont(font)
        self.sifreGosterButon.setAutoFillBackground(False)
        self.sifreGosterButon.setObjectName("sifreGosterButon")
        self.gridLayout.addWidget(self.sifreGosterButon, 11, 0, 1, 1)
        self.sifreKaydetButon = QtWidgets.QPushButton(self.tabSifreKaydetListele)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(50)
        sizePolicy.setHeightForWidth(self.sifreKaydetButon.sizePolicy().hasHeightForWidth())
        self.sifreKaydetButon.setSizePolicy(sizePolicy)
        self.sifreKaydetButon.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.sifreKaydetButon.setFont(font)
        self.sifreKaydetButon.setAutoFillBackground(False)
        self.sifreKaydetButon.setObjectName("sifreKaydetButon")
        self.gridLayout.addWidget(self.sifreKaydetButon, 9, 0, 1, 1)
        self.sekmeler.addTab(self.tabSifreKaydetListele, "")
        self.verticalLayout.addWidget(self.sekmeler)
        self.createdByDrago1 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.createdByDrago1.sizePolicy().hasHeightForWidth())
        self.createdByDrago1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Harrington")
        font.setPointSize(10)
        self.createdByDrago1.setFont(font)
        self.createdByDrago1.setAutoFillBackground(False)
        self.createdByDrago1.setStyleSheet("background-color:rgb(82, 82, 82);")
        self.createdByDrago1.setAlignment(QtCore.Qt.AlignCenter)
        self.createdByDrago1.setObjectName("createdByDrago1")
        self.verticalLayout.addWidget(self.createdByDrago1)
        sifreOlusturSifreleKaydet.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(sifreOlusturSifreleKaydet)
        self.statusbar.setAutoFillBackground(False)
        self.statusbar.setObjectName("statusbar")
        sifreOlusturSifreleKaydet.setStatusBar(self.statusbar)

        self.retranslateUi(sifreOlusturSifreleKaydet)
        self.sekmeler.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(sifreOlusturSifreleKaydet)

    def retranslateUi(self, sifreOlusturSifreleKaydet):
        _translate = QtCore.QCoreApplication.translate
        sifreOlusturSifreleKaydet.setWindowTitle(_translate("sifreOlusturSifreleKaydet", "Şifre Oluştur Kaydet"))
        self.hata_labeli.setText(_translate("sifreOlusturSifreleKaydet", "DOSYA YOLU SEÇMEDEN İŞLEM YAPMAYINIZ!"))
        self.textEditProgramAciklama.setHtml(_translate("sifreOlusturSifreleKaydet", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Times New Roman\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Times New Roman,serif\'; font-size:14pt; font-weight:600; color:#c2c2c2;\">Şifre Oluşturma: </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Times New Roman,serif\'; font-size:14pt; color:#c2c2c2;\">Şifre oluşturma ekranında; öncelikle şifre uzunluğunu rakam olarak giriniz, şifrenize dahil olmasını istediğiniz özellikleri tikleyiniz. Sonra \'Şifre Oluştur\' butonuna basarak rastgele oluşturulan şifrenizi alttaki kutucuktan kopyalayabilirsiniz.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Times New Roman,serif\'; font-size:14pt; font-weight:600; color:#c2c2c2;\">Veri Deposu: </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Times New Roman,serif\'; font-size:14pt; color:#c2c2c2;\">Herhangi bir metni açıklama ekleyerek şifrelenmiş halde depolayabilmenizi sağlar. Şifrelenmiş veriyi tekrar programı kullanarak açabilirsiniz.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Times New Roman,serif\'; font-size:14pt; color:#c2c2c2;\">Öncelikle işlemi yapabilmeniz için sonu\'.txt\' olan dosyanızı herhangibir klasörden seçebilirsiniz. Ardından kutucukları doldurarak isterseniz kayıt yapabilirsiniz veya önceden kaydedilmiş verinizi sırasıyla anahtarlarını girdikten sonra şifresini çözerek listeleyebilirsiniz.</span></p></body></html>"))
        self.sekmeler.setTabText(self.sekmeler.indexOf(self.tabAciklama), _translate("sifreOlusturSifreleKaydet", "Program Kullanım Kılavuzu"))
        self.baslik1.setText(_translate("sifreOlusturSifreleKaydet", "ŞİFRE ÖZELLİKLERİNİ SEÇİNİZ"))
        self.sifreUzunlugu_aciklama.setText(_translate("sifreOlusturSifreleKaydet", "Şifre Uzunluğu:"))
        self.turkceKarakterChbox.setText(_translate("sifreOlusturSifreleKaydet", "Türkçe Karakterler(Ü,ğ,vs)"))
        self.ozelKarakterChbox.setText(_translate("sifreOlusturSifreleKaydet", "Özel Karakterler(?,*,vs)"))
        self.rakamChbox.setText(_translate("sifreOlusturSifreleKaydet", "Rakamlar(1,2,3,vs)"))
        self.sifreOlusturButon.setText(_translate("sifreOlusturSifreleKaydet", "Şifre Oluştur"))
        self.sekmeler.setTabText(self.sekmeler.indexOf(self.tabSifreOlustur), _translate("sifreOlusturSifreleKaydet", "Şifre Oluşturma"))
        item = self.sifreListelemeTablo.horizontalHeaderItem(0)
        item.setText(_translate("sifreOlusturSifreleKaydet", "Açıklama Sütunu"))
        item = self.sifreListelemeTablo.horizontalHeaderItem(1)
        item.setText(_translate("sifreOlusturSifreleKaydet", "Metin Sütunu"))
        self.dosyaYoluLink.setText(_translate("sifreOlusturSifreleKaydet", "DOSYA YOLU BOŞ"))
        self.dosyaYoluButon.setText(_translate("sifreOlusturSifreleKaydet", "Dosya yolu seç"))
        self.sifreAciklama.setText(_translate("sifreOlusturSifreleKaydet", "Şifre Açıklaması:"))
        self.sifreAciklamaSifre.setText(_translate("sifreOlusturSifreleKaydet", "Şifrelenecek Mesaj:"))
        self.label.setText(_translate("sifreOlusturSifreleKaydet", "Anahtar (Sadece rakam):"))
        self.sifreGosterButon.setText(_translate("sifreOlusturSifreleKaydet", "Şifre Göster"))
        self.sifreKaydetButon.setText(_translate("sifreOlusturSifreleKaydet", "Şifre Kaydet"))
        self.sekmeler.setTabText(self.sekmeler.indexOf(self.tabSifreKaydetListele), _translate("sifreOlusturSifreleKaydet", "Veri Deposu"))
        self.createdByDrago1.setText(_translate("sifreOlusturSifreleKaydet", "®©DRAGO©®"))
